Repository EdySerrano/PC1-Grupo4-Proyecto8-DesarrolloDeSoftware, pull requests merged in 2025-09, with the labels that each got.

#5 Merge Checks/http y dns checks a develop
  Makefile
  src/checks.sh
Labels: Sprint1, Importante

#9 Edy serrano/mejora de bash
  src/checks.sh
Labels: Importante, Sprint-2

#13 Administracion de Procesos con systemd completado
  Makefile
  systemd/app.service
  tests/tests_basico.bats
Labels: Importante, Sprint-2

#15 Edy serrano/validacion de idempotencia
  src/checks.sh
  src/validar.sh
Labels: Sprint-3, Bash, Importante

#20 PR develop a main - Version Final Proyecto
  .gitignore
  Makefile
  docs/README.md
  src/checks.sh
  src/runner.sh
  src/validar.sh
  systemd/app.service
  tests/tests_basico.bats
Labels: Importante
